### ISSUE TITLE
데이터가 올라가지 않아요,,,

### ISSUE THREAD

**Issue by syongsyong6035** [2024-venture-suyaho/suyaho#26]
## 💭 작업 브랜치
>어디서 잘못되서 안보여지는지가 감이 안와요,,, 

## 🥲 어떤 버그인가요?
> 일단 write글쓰기를 해서 글쓰기를 하면 올려져서 list거래 페이지에 보여지지 않습니다
코드를 계속 봣는데도 어디서문제인지 모르겟어요

## 📫 어떤 상황에서 발생한 버그인가요?
> 

## 💸 예상 결과
> write게시판을 작성을 하면 게시판에 행이 추가되어 보여지게 하는것

**Comment by k168ww** [comment]
고생하셨습니다.
