### ISSUE TITLE
#30 완성

### ISSUE THREAD

**Issue by syongsyong6035** [2024-venture-suyaho/suyaho#38]
💭 작업 브랜치
[feature/deal]

🍀 기능 설명
게시판 목록  글쓰면 자동으로 추가되고 보여지는것까지 확인햇습니다

🎀 작업 상세 내용
게시판 목록 글쓰면 행 추가되게 햇구
css 자잘자잘한 기능 넣기두 햇습니다 
📈 기타
분실물 게시판은,,, 없구 그대신에 카테고리 로 넣어저 저장하게 생각햇습니다

**Comment by k168ww** [comment]
수고하셨습니다!
